#################
## DragonOps recommends creating environments (https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment).
## Environments allow users to configure `manual` jobs (this means that a deploy to production would need to be approved).
## See here for more information: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-environments-to-manually-trigger-workflow-jobs
## Users can also set MASTER_ACCOUNT_REGION, OIDC_ROLE_ARN and APP_NAME to repository-level variables and reference them as: ${{ vars.VARIBLE_NAME }}
#################

########
# This `prod` workflow will trigger when a new tag is pushed to the repo. The tag is bumped in the manually triggered `preprod` workflow,
# but a tag can be manually pushed as well to trigger this workflow. If you pass in the tag, that is the tag that will be deployed to prod.
# The app will be deployed to the prod environment.
## Note: The BuildAndPush step will trigger the update to your application code. The DeployApp step will only update
## infrastructure changes, like IAM permissions, port and command.
########
name: DeployToProd

env:
  ENVIRONMENT_NAME: prod
  IS_PROD_ENVIRONMENT: true
  MASTER_ACCOUNT_REGION: us-east-1
  OIDC_ROLE_ARN: arn:aws:iam::721481723200:role/oidc-GitHub-dragonops-ci
  APP_NAME: python-flask-restapi3

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The tag to build and push from
  push:
    tags:
      - '*'
      -
#if: "${{ github.event.inputs.<INPUT_NAME> != '' }}"
jobs:
  BuildAndPush:
    #    environment: $ENVIRONMENT_NAME
    uses: ./.github/workflows/build-and-push.yml
    with:
      MASTER_ACCOUNT_REGION: $MASTER_ACCOUNT_REGION
      ENVIRONMENT_NAME: $ENVIRONMENT_NAME
      OIDC_ROLE_ARN: $OIDC_ROLE_ARN
      APP_NAME: $APP_NAME
      IS_PROD_ENVIRONMENT: $IS_PROD_ENVIRONMENT
      TAG_OVERRIDE: ${{ github.event.inputs.tag }} #TODO figure this out in argo

  DeployApp:
    #    environment: $ENVIRONMENT_NAME
    uses: ./.github/workflows/deploy-app.yml