#################
## DragonOps recommends creating environments (https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment).
## Environments allow users to configure `manual` jobs (this means that a deploy to production would need to be approved).
## See here for more information: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-environments-to-manually-trigger-workflow-jobs
## Users can also set MASTER_ACCOUNT_REGION, OIDC_ROLE_ARN and APP_NAME to repository-level variables and reference them as: ${{ vars.VARIBLE_NAME }}
#################

########
# This `preprod` workflow will trigger only when the a user manually triggers it in the UI from the master, main, prod or production branch..
# The app will be deployed to the preprod environment.
# NOTE: Once this workflow is triggered, the PROD workflow will also be triggered and will deploy to the prod environment.
## Note: The BuildAndPush step will trigger the update to your application code. The DeployApp step will only update
## infrastructure changes, like IAM permissions, port and command.
########
name: DeployToPreProd

env:
  ENVIRONMENT_NAME: preprod
  IS_PROD_ENVIRONMENT: false
  MASTER_ACCOUNT_REGION: us-east-1
  OIDC_ROLE_ARN: arn:aws:iam::721481723200:role/oidc-GitHub-dragonops-ci
  APP_NAME: python-flask-restapi3

on:
  workflow_dispatch:
    branches:
      - "master"
      - "main"
      - "prod"
      - "production"

jobs:
  # Bump tag will run if the environment is equal to the prod environment & a GitHub Token exists.
  BumpTag:
    if: GITHUB_TOKEN exists # TODO -- this will also trigger the prod workflow
    uses: ./.github/workflows/bump-tag.yml

  BuildAndPush:
    #    environment: $ENVIRONMENT_NAME
    needs: BumpTag
    uses: ./.github/workflows/build-and-push.yml
    with:
      MASTER_ACCOUNT_REGION: $MASTER_ACCOUNT_REGION
      ENVIRONMENT_NAME: $ENVIRONMENT_NAME
      OIDC_ROLE_ARN: $OIDC_ROLE_ARN
      APP_NAME: $APP_NAME
      IS_PROD_ENVIRONMENT: $IS_PROD_ENVIRONMENT

  DeployApp:
    #    environment: $ENVIRONMENT_NAME
    uses: ./.github/workflows/deploy-app.yml